update: quick refactor to get pr working
liwoo/family-contributions pull request #2
Opened 2024-03-21 12:48 UTC by glenmiracle18

**_changes made:_**
This was just a quick pr to test if everthing is woking well

2024-03-21 21:57 UTC, liwoo requested changes
why are we removing these icons?

2024-03-25 15:05 UTC, glenmiracle18 commented
> why are we removing these icons?

Those Icons were imported but never used.

2024-04-08 11:01 UTC, glenmiracle18 commented
Hello @liwoo, I just did some final refactor changes to the codebase.
Mind taking a look?

2024-04-09 21:55 UTC, liwoo requested changes
mostly need to fix naming convention issues

2024-04-09 21:55 UTC, liwoo commented on app/components/widgets/Notification-dropdown.tsx
> +import { Dropdown } from "flowbite-react";
the name of this should be `NotificationDropdown`

2024-04-09 21:55 UTC, liwoo commented on app/components/svgs/search-icon.tsx
> +export const SearchIcon = () => {
should be `SearchIcon`

2024-04-09 21:55 UTC, liwoo commented on app/components/blocks/sidebar.tsx
> +          <Link
this can be made into a component because the `Settings` is also the exact same code

2024-04-09 21:55 UTC, liwoo commented on app/components/widgets/WithSideView.tsx
> +      // checks is the location is currently in create
this comment is self explanatory

2024-04-09 21:55 UTC, liwoo commented on app/components/widgets/WithSideView.tsx
> +        // checks is the location is currently in edit
so it this comment

2024-04-09 21:55 UTC, liwoo commented on app/components/widgets/WithSideView.tsx
> +        // checks is the location is currently in view
and this

2024-04-09 21:55 UTC, liwoo commented on app/components/widgets/search-box.tsx
> +import { SearchIcon } from "../svgs/search-icon";
must be in `components/widgets/navigation/SearchBox.tsx`

2024-04-11 22:17 UTC, glenmiracle18 commented
> mostly need to fix naming convention issues

Okay. Thanks for the feedback. I'll clean it up and update the pr

2024-04-15 14:03 UTC, glenmiracle18 commented
Hello Sir,
I just did the changes you reviewed above. 
I have also added the dark theme toggler.
Credit to the flowbite documentation.
Let me know what you think, and if we can mover forward with the next pr. 😇

2024-04-25 17:22 UTC, liwoo requested changes
few more changes then we're good

2024-04-25 17:22 UTC, liwoo commented on app/components/blocks/SidebarCta.tsx
> +        <Link
this could be a `SidebarAction` that takes an `href`, `icon` and `onClick`

2024-04-25 17:22 UTC, liwoo commented on app/components/blocks/SidebarCta.tsx
> +        <Tooltip
can still be broken down into its own component

2024-04-25 17:22 UTC, liwoo commented on app/components/blocks/SidebarTheme.tsx
> +export const SidebarTheme = {
we can create a component called `app/theme/overrides` -> `app/theme/overrides/sidebar`

2024-04-25 17:22 UTC, liwoo commented on app/components/widgets/NotificationDropdown.tsx
> +            name@gmail.com
remove the `email` and `name` and pass it as props

2024-04-25 17:22 UTC, liwoo commented on app/components/widgets/NotificationDropdown.tsx
> +        <Dropdown.Item>Sign out</Dropdown.Item>
this can also be removed so we pass it as part of props

2024-04-25 17:22 UTC, liwoo commented on app/components/widgets/WithSideView.tsx
> +  const [title, setTitle] = useState("");
lets pass the correct data type to the useState generic, i.e. `useState<string>`

2024-04-25 17:22 UTC, liwoo commented on app/components/widgets/WithSideView.tsx
> +    const title = isCreate
clean up this nested ternary

2024-04-30 21:53 UTC, liwoo approved these changes

2024-04-30 21:53 UTC, merged